const crypto = require('crypto');
const NutritionMenu = require('../models/NutritionMenu');
const User = require('../models/User');
const { OnboardingNutritionMenuRequest } = require('./requests');
const { isLegacyAutogeneratedNutritionMenuEntry } = require('../utils/nutritionMenuUtils');
const {
    normalizeImportedNutritionMenuPeriods,
    normalizePeriodToken,
} = require('../utils/nutritionMealPeriods');

const DEFAULT_MAX_OUTPUT_TOKENS = 6000;
const DEFAULT_RATE_LIMIT_RETRY_DELAY_MS = 15000;
const DEFAULT_RATE_LIMIT_MAX_RETRIES = 2;

function parseBoolean(value, fallback = true) {
    if (value === undefined || value === null || value === '') return fallback;
    return String(value).trim().toLowerCase() === 'true';
}

function parseIntOrFallback(value, fallback) {
    const parsed = Number.parseInt(value, 10);
    return Number.isFinite(parsed) ? parsed : fallback;
}

function sanitizeErrorMessage(error) {
    const message = String(error?.message || 'Nutrition menu planner failed.');
    return message.length > 400 ? `${message.slice(0, 397)}...` : message;
}

function isRateLimitError(error) {
    if (Number(error?.status) === 429) return true;
    const message = String(error?.message || '').toLowerCase();
    return (
        message.includes('429')
        || message.includes('rate limit')
        || message.includes('too many requests')
    );
}

function sanitizeCustomNutritionMenu(entries) {
    if (!Array.isArray(entries)) return [];
    const sanitized = entries
        .slice(0, 30)
        .map((entry) => ({
            meal_period: String(entry?.meal_period || entry?.period || '').trim(),
            meal_name: String(entry?.meal_name || entry?.name || '').trim().slice(0, 160),
            total_calories: Number(entry?.total_calories || entry?.calories || 0),
            total_protein: Number(entry?.total_protein || entry?.protein || 0) || undefined,
            total_carbs: Number(entry?.total_carbs || entry?.carbs || 0) || undefined,
            total_fat: Number(entry?.total_fat || entry?.fat || 0) || undefined,
            note: String(entry?.note || '').trim().slice(0, 500) || undefined,
            foods: Array.isArray(entry?.foods) ? entry.foods : [],
        }))
        .filter((entry) => entry.meal_name && entry.total_calories > 0);
    return normalizeImportedNutritionMenuPeriods(sanitized);
}

function countDistinctMealPeriods(entries) {
    return new Set(
        (Array.isArray(entries) ? entries : [])
            .map((entry) => normalizePeriodToken(entry?.meal_period || entry?.period))
            .filter(Boolean)
    ).size;
}

function buildCustomNutritionMenuSignature(entries) {
    return crypto
        .createHash('sha256')
        .update(JSON.stringify(Array.isArray(entries) ? entries : []))
        .digest('hex');
}

class OnboardingNutritionMenuService {
    constructor({
        menuRequest,
        userModel = User,
        nutritionMenuModel = NutritionMenu,
        logger = console,
        enabled,
    } = {}) {
        this.logger = logger;
        this.UserModel = userModel;
        this.NutritionMenuModel = nutritionMenuModel;
        this.enabled = enabled ?? parseBoolean(process.env.ONBOARDING_AI_MENU_AUTOGEN_ENABLED, true);
        this.inFlightByUser = new Map();
        this.retryTimersByUser = new Map();
        this.maxOutputTokens = parseIntOrFallback(
            process.env.ONBOARDING_AI_PLANNER_MAX_OUTPUT_TOKENS,
            DEFAULT_MAX_OUTPUT_TOKENS
        );
        this.rateLimitRetryDelayMs = parseIntOrFallback(
            process.env.ONBOARDING_AI_PLANNER_RATE_LIMIT_RETRY_DELAY_MS,
            DEFAULT_RATE_LIMIT_RETRY_DELAY_MS
        );
        this.maxRateLimitRetries = parseIntOrFallback(
            process.env.ONBOARDING_AI_PLANNER_RATE_LIMIT_MAX_RETRIES,
            DEFAULT_RATE_LIMIT_MAX_RETRIES
        );
        this.menuRequest = menuRequest || new OnboardingNutritionMenuRequest({
            maxOutputTokens: this.maxOutputTokens,
        });
    }

    isEnabled() {
        return this.enabled;
    }

    shouldGenerateForProfile(profile = {}) {
        if (!profile || profile.onboarding_completed !== true) return false;
        const choice = String(profile.nutrition_plan_choice || '').trim().toLowerCase();
        return Boolean(choice && choice !== 'tracking_only');
    }

    clearScheduledRetry(userId) {
        const userKey = String(userId || '').trim();
        const timer = this.retryTimersByUser.get(userKey);
        if (timer) {
            clearTimeout(timer);
            this.retryTimersByUser.delete(userKey);
        }
    }

    scheduleRateLimitRetry({ userId, requestId, trigger, attempt }) {
        const userKey = String(userId || '').trim();
        if (!userKey) return false;
        if (attempt > this.maxRateLimitRetries) return false;
        if (this.retryTimersByUser.has(userKey)) return true;

        const delayMs = this.rateLimitRetryDelayMs * attempt;
        const timer = setTimeout(async () => {
            this.retryTimersByUser.delete(userKey);
            try {
                await this.ensureMenuForUser({
                    userId: userKey,
                    requestId,
                    trigger: `${trigger || 'onboarding'}_rate_limit_retry_${attempt}`,
                    force: true,
                    rateLimitAttempt: attempt,
                });
            } catch (error) {
                this.logger.error?.('onboarding.nutrition.retry_unhandled', {
                    requestId,
                    userId: userKey,
                    trigger,
                    attempt,
                    error: sanitizeErrorMessage(error),
                });
            }
        }, delayMs);

        this.retryTimersByUser.set(userKey, timer);
        this.logger.info?.('onboarding.nutrition.retry_scheduled', {
            requestId,
            userId: userKey,
            trigger,
            attempt,
            delayMs,
        });
        return true;
    }

    async generateMenu({ userId, requestId, trigger, userProfile, likedFoods, dislikedFoods }) {
        return this.menuRequest.execute({ userId, requestId, trigger, userProfile, likedFoods, dislikedFoods });
    }

    async ensureMenuForUser(params = {}) {
        const userKey = String(params.userId || '').trim();
        if (!userKey) {
            return this.ensureMenuForUserInternal(params);
        }

        if (this.inFlightByUser.has(userKey)) {
            return this.inFlightByUser.get(userKey);
        }

        const promise = this.ensureMenuForUserInternal(params)
            .finally(() => {
                this.inFlightByUser.delete(userKey);
            });

        this.inFlightByUser.set(userKey, promise);
        return promise;
    }

    async ensureMenuForUserInternal({
        userId,
        requestId,
        trigger = 'onboarding',
        profile: incomingProfile,
        force = false,
        rateLimitAttempt = 0,
    }) {
        if (!userId) {
            return { triggered: false, status: 'skipped', reason: 'missing_user_id' };
        }

        const user = await this.UserModel.findById(userId);
        if (!user) {
            return { triggered: false, status: 'skipped', reason: 'user_not_found' };
        }

        const currentProfile = incomingProfile || user.profile || {};

        if (!force && !this.shouldGenerateForProfile(currentProfile)) {
            return { triggered: false, status: 'skipped', reason: 'profile_not_eligible' };
        }

        const nutritionPlanChoice = String(currentProfile?.nutrition_plan_choice || '').trim().toLowerCase();

        if (nutritionPlanChoice === 'tracking_only' || !nutritionPlanChoice) {
            user.profile = {
                ...(user.profile || {}),
                nutrition_plan_status: 'skipped',
                nutrition_plan_error: undefined,
                nutrition_plan_source: 'none',
            };
            await user.save();
            this.logger.info?.('onboarding.nutrition.skipped', {
                requestId,
                userId: String(user._id),
                trigger,
                reason: 'tracking_only_or_missing_choice',
            });
            return { triggered: false, status: 'skipped', reason: 'tracking_only_or_missing_choice' };
        }

        const sanitizedCustomMenu = sanitizeCustomNutritionMenu(currentProfile?.custom_nutrition_menu);
        const existingMenuCount = await this.NutritionMenuModel.countDocuments({
            user: user._id,
            archived: { $ne: true },
        });

        try {
            if (nutritionPlanChoice === 'existing') {
                if (sanitizedCustomMenu.length > 0) {
                    const now = new Date();
                    const importSignature = buildCustomNutritionMenuSignature(sanitizedCustomMenu);
                    const existingImportedEntries = await this.NutritionMenuModel.find({
                        user: user._id,
                        archived: { $ne: true },
                        import_origin: 'onboarding_custom_menu',
                    })
                        .select('import_signature')
                        .lean();
                    const hasSameImportedMenu = existingImportedEntries.length > 0
                        && existingImportedEntries.every((e) => e.import_signature === importSignature);

                    if (hasSameImportedMenu) {
                        user.profile = {
                            ...(user.profile || {}),
                            meal_frequency: countDistinctMealPeriods(sanitizedCustomMenu) || user.profile?.meal_frequency,
                            nutrition_plan_status: 'ready',
                            nutrition_plan_error: undefined,
                            nutrition_plan_source: 'manual',
                            nutrition_plan_generated_at: user.profile?.nutrition_plan_generated_at || now,
                        };
                        await user.save();
                        this.logger.info?.('onboarding.nutrition.ready', {
                            requestId,
                            userId: String(user._id),
                            trigger,
                            choice: 'existing',
                            insertedCount: 0,
                            existingMenuCountBefore: existingMenuCount,
                            reason: 'custom_menu_already_saved',
                        });
                        return { triggered: false, status: user.profile.nutrition_plan_status, reason: 'custom_menu_already_saved' };
                    }

                    if (existingImportedEntries.length > 0) {
                        await this.NutritionMenuModel.updateMany({
                            user: user._id,
                            archived: { $ne: true },
                            import_origin: 'onboarding_custom_menu',
                        }, { $set: { archived: true } });
                    }

                    await this.NutritionMenuModel.insertMany(sanitizedCustomMenu.map((entry) => ({
                        user: user._id,
                        date: now,
                        meal_period: entry.meal_period,
                        meal_name: entry.meal_name,
                        source: 'existing',
                        total_calories: entry.total_calories,
                        total_protein: entry.total_protein,
                        total_carbs: entry.total_carbs,
                        total_fat: entry.total_fat,
                        note: entry.note,
                        foods: entry.foods,
                        import_origin: 'onboarding_custom_menu',
                        import_signature: importSignature,
                    })));

                    user.profile = {
                        ...(user.profile || {}),
                        meal_frequency: countDistinctMealPeriods(sanitizedCustomMenu) || user.profile?.meal_frequency,
                        nutrition_plan_status: 'ready',
                        nutrition_plan_error: undefined,
                        nutrition_plan_source: 'manual',
                        nutrition_plan_generated_at: new Date(),
                    };
                } else {
                    user.profile = {
                        ...(user.profile || {}),
                        nutrition_plan_status: existingMenuCount > 0 ? 'ready' : 'skipped',
                        nutrition_plan_error: undefined,
                        nutrition_plan_source: 'manual',
                    };
                }

                await user.save();
                this.logger.info?.('onboarding.nutrition.ready', {
                    requestId,
                    userId: String(user._id),
                    trigger,
                    choice: 'existing',
                    insertedCount: sanitizedCustomMenu.length,
                    existingMenuCountBefore: existingMenuCount,
                    status: user.profile.nutrition_plan_status,
                });
                return {
                    triggered: true,
                    status: user.profile.nutrition_plan_status,
                    reason: sanitizedCustomMenu.length > 0 ? 'custom_menu_saved' : 'no_custom_menu_provided',
                };
            }

            if (nutritionPlanChoice === 'ai') {
                if (!this.isEnabled()) {
                    return { triggered: false, status: 'skipped', reason: 'menu_autogen_disabled' };
                }

                const existingMenuEntries = await this.NutritionMenuModel.find({
                    user: user._id,
                    archived: { $ne: true },
                })
                    .select('source note foods')
                    .lean();

                const visibleMenuEntries = existingMenuEntries.filter(
                    (entry) => !isLegacyAutogeneratedNutritionMenuEntry(entry)
                );
                const hasVisibleAiMenus = visibleMenuEntries.some(
                    (entry) => String(entry?.source || '').trim().toLowerCase() === 'ai'
                );

                if (visibleMenuEntries.length === 0) {
                    const generatedAt = new Date();

                    user.profile = {
                        ...(user.profile || {}),
                        nutrition_plan_status: 'generating',
                        nutrition_plan_error: undefined,
                        nutrition_plan_source: 'agent',
                    };
                    await user.save();

                    const { createdCount, provider, model } = await this.generateMenu({
                        userId: String(user._id),
                        requestId,
                        trigger,
                        userProfile: user.profile || {},
                        likedFoods: user.liked_foods || [],
                        dislikedFoods: user.disliked_foods || [],
                    });

                    const savedEntries = await this.NutritionMenuModel.find({
                        user: user._id,
                        archived: { $ne: true },
                    }).select('meal_period').lean();

                    user.profile = {
                        ...(user.profile || {}),
                        meal_frequency: countDistinctMealPeriods(savedEntries) || user.profile?.meal_frequency,
                        nutrition_plan_status: 'ready',
                        nutrition_plan_error: undefined,
                        nutrition_plan_source: 'agent',
                        nutrition_plan_generated_at: generatedAt,
                    };
                    await user.save();
                    this.clearScheduledRetry(user._id);

                    this.logger.info?.('onboarding.nutrition.ready', {
                        requestId,
                        userId: String(user._id),
                        trigger,
                        choice: 'ai',
                        existingMenuCountBefore: existingMenuCount,
                        createdCount,
                        status: user.profile.nutrition_plan_status,
                        reason: 'ai_menu_generated',
                        provider,
                        model,
                    });
                    return {
                        triggered: true,
                        status: user.profile.nutrition_plan_status,
                        reason: 'ai_menu_generated',
                        createdCount,
                    };
                }

                user.profile = {
                    ...(user.profile || {}),
                    nutrition_plan_status: 'ready',
                    nutrition_plan_error: undefined,
                    nutrition_plan_source: hasVisibleAiMenus ? 'agent' : 'manual',
                    nutrition_plan_generated_at: user.profile?.nutrition_plan_generated_at || new Date(),
                };
                await user.save();
                this.logger.info?.('onboarding.nutrition.ready', {
                    requestId,
                    userId: String(user._id),
                    trigger,
                    choice: 'ai',
                    existingMenuCountBefore: existingMenuCount,
                    visibleMenuCount: visibleMenuEntries.length,
                    status: user.profile.nutrition_plan_status,
                    reason: 'existing_visible_menu_preserved',
                });
                return {
                    triggered: false,
                    status: user.profile.nutrition_plan_status,
                    reason: 'existing_visible_menu_preserved',
                };
            }

            this.logger.info?.('onboarding.nutrition.skipped', {
                requestId,
                userId: String(user._id),
                trigger,
                reason: 'unsupported_nutrition_choice',
                nutritionPlanChoice,
            });
            return { triggered: false, status: 'skipped', reason: 'unsupported_nutrition_choice' };

        } catch (error) {
            const errorMessage = sanitizeErrorMessage(error);

            if (isRateLimitError(error)) {
                const nextAttempt = rateLimitAttempt + 1;
                const retryScheduled = this.scheduleRateLimitRetry({
                    userId: user._id,
                    requestId,
                    trigger,
                    attempt: nextAttempt,
                });
                user.profile = {
                    ...(user.profile || {}),
                    nutrition_plan_status: retryScheduled ? 'pending' : 'failed',
                    nutrition_plan_error: retryScheduled
                        ? `Rate-limited (429). Retrying automatically (${nextAttempt}/${this.maxRateLimitRetries}).`
                        : 'Rate-limited (429). Max retries exceeded.',
                };
                await user.save();
                this.logger.warn?.('onboarding.nutrition.rate_limited', {
                    requestId,
                    userId: String(user._id),
                    trigger,
                    error: errorMessage,
                    retryScheduled,
                    nextAttempt: retryScheduled ? nextAttempt : null,
                });
                return { triggered: true, status: 'pending', retryable: true, retryScheduled };
            }

            this.clearScheduledRetry(user._id);
            user.profile = {
                ...(user.profile || {}),
                nutrition_plan_status: 'failed',
                nutrition_plan_error: errorMessage,
            };
            await user.save();
            this.logger.error?.('onboarding.nutrition.failed', {
                requestId,
                userId: String(user._id),
                trigger,
                error: errorMessage,
            });
            return { triggered: true, status: 'failed', error: errorMessage };
        }
    }
}

module.exports = OnboardingNutritionMenuService;
