const asyncHandler = require('express-async-handler');
const axios = require('axios');
const NutritionLog = require('../models/NutritionLog');
const NutritionMenu = require('../models/NutritionMenu');
const { isLegacyAutogeneratedNutritionMenuEntry } = require('../utils/nutritionMenuUtils');
const { createChatProvider } = require('../ai/providers');

// @desc    Get nutrition logs
// @route   GET /api/nutrition
// @access  Private
const getNutritionLogs = asyncHandler(async (req, res) => {
    const logs = await NutritionLog.find({
        user: req.user.id,
        archived: { $ne: true },
    }).sort({ date: -1, createdAt: -1 });

    res.status(200).json(logs);
});

// @desc    Log meal
// @route   POST /api/nutrition
// @access  Private
const logMeal = asyncHandler(async (req, res) => {
    const {
        date,
        meal_name,
        meal_period,
        source,
        calories,
        protein,
        carbs,
        fat,
        foods,
    } = req.body || {};

    if (!meal_name || calories === undefined || calories === null) {
        res.status(400);
        throw new Error('meal_name and calories are required.');
    }

    const log = await NutritionLog.create({
        user: req.user.id,
        date: date ? new Date(date) : new Date(),
        meal_name,
        meal_period: meal_period || '',
        source: source || 'manual',
        calories,
        protein: protein || 0,
        carbs: carbs || 0,
        fat: fat || 0,
        foods: Array.isArray(foods) ? foods : [],
    });

    res.status(200).json(log);
});

// @desc    Archive one nutrition log entry
// @route   DELETE /api/nutrition/entry/:id
// @access  Private
const deleteNutritionLog = asyncHandler(async (req, res) => {
    const log = await NutritionLog.findOne({
        _id: req.params.id,
        user: req.user.id,
        archived: { $ne: true },
    });

    if (!log) {
        res.status(404);
        throw new Error('Nutrition log not found.');
    }

    log.archived = true;
    await log.save();

    res.status(200).json({ archived: true, id: String(log._id) });
});

// @desc    Get logs by date
// @route   GET /api/nutrition/:date
// @access  Private
const getLogsByDate = asyncHandler(async (req, res) => {
    const start = new Date(req.params.date);
    start.setHours(0, 0, 0, 0);

    const end = new Date(req.params.date);
    end.setHours(23, 59, 59, 999);

    const logs = await NutritionLog.find({
        user: req.user.id,
        archived: { $ne: true },
        date: {
            $gte: start,
            $lte: end
        }
    }).sort({ createdAt: 1 });

    res.status(200).json(logs);
});

// @desc    Save menu/meal template for the user
// @route   POST /api/nutrition/menu
// @access  Private
const saveNutritionMenu = asyncHandler(async (req, res) => {
    const {
        date,
        meal_period = '',
        meal_name,
        source = 'manual',
        total_calories,
        total_protein = 0,
        total_carbs = 0,
        total_fat = 0,
        note = '',
        foods = [],
    } = req.body || {};

    if (!meal_name || total_calories === undefined || total_calories === null) {
        res.status(400);
        throw new Error('meal_name and total_calories are required.');
    }

    const menuEntry = await NutritionMenu.create({
        user: req.user.id,
        date: date ? new Date(date) : new Date(),
        meal_period,
        meal_name,
        source,
        total_calories,
        total_protein,
        total_carbs,
        total_fat,
        note,
        foods: Array.isArray(foods) ? foods : [],
    });

    res.status(201).json(menuEntry);
});

// @desc    Get saved menu entries (optionally for a specific date)
// @route   GET /api/nutrition/menu
// @access  Private
const getNutritionMenu = asyncHandler(async (req, res) => {
    const { date } = req.query;
    const query = {
        user: req.user.id,
        archived: { $ne: true },
    };

    if (date) {
        const start = new Date(date);
        const end = new Date(date);
        start.setHours(0, 0, 0, 0);
        end.setHours(23, 59, 59, 999);
        query.date = { $gte: start, $lte: end };
    }

    const menuEntries = await NutritionMenu.find(query)
        .sort({ date: -1, createdAt: -1 })
        .limit(200);

    const visibleMenuEntries = menuEntries.filter((entry) => !isLegacyAutogeneratedNutritionMenuEntry(entry));

    res.status(200).json(visibleMenuEntries);
});

function buildMealSuggestionSystem() {
    return [
        'You are a nutrition assistant generating a single meal suggestion.',
        'Return valid JSON only. No explanation or text outside the JSON.',
        'Use realistic portions and accurate macro totals.',
        'Respect the diet type and avoid disliked foods.',
    ].join('\n');
}

function buildMealSuggestionUserMessage({
    meal_period, goal, diet_type, time_of_day,
    target_calories_per_meal, target_protein, target_carbs, target_fat,
    liked_food_names, disliked_food_names,
}) {
    return `Generate a ${meal_period} meal suggestion.

Targets for this meal:
- Calories: ~${target_calories_per_meal} kcal
- Protein: ~${target_protein}g
- Carbs: ~${target_carbs}g
- Fat: ~${target_fat}g

User context:
- Goal: ${goal}
- Diet type: ${diet_type}
- Time: ${time_of_day}
- Preferred foods (use if suitable): ${liked_food_names}
- Avoid: ${disliked_food_names}

Return this exact JSON shape:
{
  "meal_name": "Name of the meal",
  "foods": [
    { "name": "Food name", "portion": "Xg", "calories": 0, "protein": 0, "carbs": 0, "fat": 0 }
  ],
  "total_calories": 0,
  "total_protein": 0,
  "total_carbs": 0,
  "total_fat": 0,
  "coach_note": "Short motivational note based on the goal"
}`;
}

// @desc    Generate a meal suggestion via LLM
// @route   POST /api/nutrition/meal-plan
// @access  Private
const generateMealPlan = asyncHandler(async (req, res) => {
    const {
        liked_foods = [],
        disliked_foods = [],
        remaining_calories = 2000,
        protein_goal = 150, protein_consumed = 0,
        carbs_goal = 200, carbs_consumed = 0,
        fat_goal = 65, fat_consumed = 0,
        time_of_day = '12:00',
        meal_period = 'Lunch',
        meals_eaten_today = 0,
        total_meals_planned = 4,
        diet_type = 'everything',
        goal = 'recomp',
    } = req.body;

    const meals_remaining = Math.max(1, total_meals_planned - meals_eaten_today);
    const target_calories_per_meal = Math.round(remaining_calories / meals_remaining);
    const target_protein = Math.round(Math.max(0, protein_goal - protein_consumed) / meals_remaining);
    const target_carbs = Math.round(Math.max(0, carbs_goal - carbs_consumed) / meals_remaining);
    const target_fat = Math.round(Math.max(0, fat_goal - fat_consumed) / meals_remaining);

    const liked_food_names = liked_foods.slice(0, 15).map(f => f.name).join(', ') || 'none';
    const disliked_food_names = (Array.isArray(disliked_foods) ? disliked_foods : []).slice(0, 10).join(', ') || 'none';

    const provider = createChatProvider();
    const completion = await provider.generateSafe({
        system: buildMealSuggestionSystem(),
        messages: [{
            role: 'user',
            content: buildMealSuggestionUserMessage({
                meal_period, goal, diet_type, time_of_day,
                target_calories_per_meal, target_protein, target_carbs, target_fat,
                liked_food_names, disliked_food_names,
            }),
        }],
        userId: String(req.user.id),
        options: {
            temperature: 0.3,
            responseFormat: 'json_object',
            maxTokens: 800,
        },
    });

    const meal = JSON.parse(completion.text || '');
    res.status(200).json(meal);
});

// @desc    Proxy OpenFoodFacts search (avoids browser CORS + HTTP2 limits)
// @route   POST /api/nutrition/foods
// @access  Private
const fetchFoods = asyncHandler(async (req, res) => {
    const { queries = [] } = req.body;

    const results = await Promise.allSettled(
        queries.map(q =>
            axios.get('https://world.openfoodfacts.org/cgi/search.pl', {
                params: {
                    search_terms: q,
                    json: 1,
                    page_size: 3,
                    fields: 'product_name,image_front_url,image_front_thumb_url,nutriments,brands'
                },
                timeout: 8000,
                headers: { 'User-Agent': 'TrainerApp/1.0' }
            })
                .then(r => r.data.products || [])
                .catch(() => [])
        )
    );

    const products = results.flatMap(r => r.status === 'fulfilled' ? r.value : []);
    res.json({ products });
});

module.exports = {
    getNutritionLogs,
    logMeal,
    deleteNutritionLog,
    getLogsByDate,
    saveNutritionMenu,
    getNutritionMenu,
    generateMealPlan,
    fetchFoods,
};
