const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const asyncHandler = require('express-async-handler');
const User = require('../models/User');
const NutritionMenu = require('../models/NutritionMenu');
const OnboardingWorkoutPlannerService = require('../services/onboardingWorkoutPlannerService');
const { isLegacyAutogeneratedNutritionMenuEntry } = require('../utils/nutritionMenuUtils');
const onboardingNutritionMenuBuilder = require('../utils/onboardingNutritionMenuBuilder');

const onboardingWorkoutPlannerService = new OnboardingWorkoutPlannerService();

const generateToken = (id) => {
    return jwt.sign({ id }, process.env.JWT_SECRET, {
        expiresIn: '30d',
    });
};

function clampNumber(value, min, max, fallback) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) return fallback;
    return Math.min(max, Math.max(min, parsed));
}

function cleanText(value, maxLen = 200) {
    return String(value || '').trim().slice(0, maxLen);
}

function normalizeTrainerPersonality(value) {
    if (value === undefined || value === null || value === '') return undefined;
    const normalized = String(value).trim().toLowerCase();
    const aliases = {
        drill_sergeant: 'drill_sergeant_coach',
        scientist: 'scientist_coach',
        nutritionist: 'nutritionist',
        zen: 'zen_coach',
        zen_coach: 'zen_coach',
        drill_sergeant_coach: 'drill_sergeant_coach',
        scientist_coach: 'scientist_coach',
    };
    return aliases[normalized] || 'drill_sergeant_coach';
}

function sanitizeMenuFoods(foods) {
    if (!Array.isArray(foods)) return [];
    return foods
        .slice(0, 20)
        .map((food) => ({
            name: cleanText(food?.name, 120),
            portion: cleanText(food?.portion, 60),
            calories: clampNumber(food?.calories, 0, 5000, 0),
            protein: clampNumber(food?.protein, 0, 1000, 0),
            carbs: clampNumber(food?.carbs, 0, 1000, 0),
            fat: clampNumber(food?.fat, 0, 1000, 0),
        }))
        .filter((food) => food.name);
}

function sanitizeCustomNutritionMenu(entries) {
    if (!Array.isArray(entries)) return [];
    return entries
        .slice(0, 30)
        .map((entry) => ({
            meal_name: cleanText(entry?.meal_name || entry?.name, 160),
            meal_period: cleanText(entry?.meal_period || entry?.period, 80),
            total_calories: clampNumber(entry?.total_calories ?? entry?.calories, 1, 10000, 0),
            total_protein: clampNumber(entry?.total_protein ?? entry?.protein, 0, 1500, 0),
            total_carbs: clampNumber(entry?.total_carbs ?? entry?.carbs, 0, 1500, 0),
            total_fat: clampNumber(entry?.total_fat ?? entry?.fat, 0, 1500, 0),
            note: cleanText(entry?.note, 500),
            foods: sanitizeMenuFoods(entry?.foods),
        }))
        .filter((entry) => entry.meal_name && entry.total_calories > 0);
}

function countDistinctMealPeriods(entries) {
    return new Set(
        (Array.isArray(entries) ? entries : [])
            .map((entry) => cleanText(entry?.meal_period || entry?.period, 80))
            .filter(Boolean)
    ).size;
}

function normalizeIncomingProfile(profile = {}) {
    const normalized = { ...(profile || {}) };

    if (Object.hasOwn(normalized, 'trainer_personality')) {
        normalized.trainer_personality = normalizeTrainerPersonality(normalized.trainer_personality);
    }

    const hasWorkoutPlanChoice = typeof normalized.plan_choice === 'string';
    const planChoice = hasWorkoutPlanChoice
        ? String(normalized.plan_choice || '').trim().toLowerCase()
        : '';

    if (hasWorkoutPlanChoice) {
        if (planChoice === 'existing') {
            normalized.workout_plan_status = 'skipped';
            normalized.workout_plan_error = undefined;
        }
        if (planChoice === 'ai' && normalized.onboarding_completed === true) {
            normalized.workout_plan_status = normalized.workout_plan_status || 'pending';
        }
    }

    const hasNutritionPlanChoice = typeof normalized.nutrition_plan_choice === 'string';
    const nutritionPlanChoice = hasNutritionPlanChoice
        ? String(normalized.nutrition_plan_choice || '').trim().toLowerCase()
        : '';

    if (hasNutritionPlanChoice) {
        if (nutritionPlanChoice === 'existing') {
            normalized.nutrition_plan_status = 'skipped';
            normalized.nutrition_plan_error = undefined;
            normalized.nutrition_plan_source = 'manual';
        }
        if (nutritionPlanChoice === 'tracking_only') {
            normalized.nutrition_plan_status = 'skipped';
            normalized.nutrition_plan_error = undefined;
            normalized.nutrition_plan_source = 'none';
        }
        if (nutritionPlanChoice === 'ai' && normalized.onboarding_completed === true) {
            normalized.nutrition_plan_status = normalized.nutrition_plan_status || 'pending';
            normalized.nutrition_plan_error = undefined;
            normalized.nutrition_plan_source = normalized.nutrition_plan_source || 'none';
        }
    }

    return normalized;
}

async function runOnboardingPlannerSafely({ userId, requestId, trigger }) {
    try {
        return await onboardingWorkoutPlannerService.ensurePlanForUser({
            userId,
            requestId,
            trigger,
        });
    } catch (error) {
        console.error('userController.onboardingPlanner error:', {
            userId,
            requestId,
            trigger,
            message: error?.message,
        });
        return {
            triggered: false,
            status: 'failed_to_start',
        };
    }
}

async function runOnboardingNutritionPlannerSafely({ userId, requestId, trigger, profile }) {
    if (!userId) {
        return {
            triggered: false,
            status: 'skipped',
            reason: 'missing_user_id',
        };
    }

    const user = await User.findById(userId);
    if (!user) {
        return {
            triggered: false,
            status: 'skipped',
            reason: 'user_not_found',
        };
    }

    const currentProfile = profile || user.profile || {};
    const onboardingCompleted = currentProfile?.onboarding_completed === true;
    if (!onboardingCompleted) {
        return {
            triggered: false,
            status: 'skipped',
            reason: 'onboarding_not_completed',
        };
    }

    const nutritionPlanChoice = String(currentProfile?.nutrition_plan_choice || '').trim().toLowerCase();
    if (!nutritionPlanChoice || nutritionPlanChoice === 'tracking_only') {
        user.profile = {
            ...(user.profile || {}),
            nutrition_plan_status: 'skipped',
            nutrition_plan_error: undefined,
            nutrition_plan_source: 'none',
        };
        await user.save();
        console.info('onboarding.nutrition.skipped', {
            requestId,
            userId: String(user._id),
            trigger,
            reason: 'tracking_only_or_missing_choice',
            nutritionPlanChoice: nutritionPlanChoice || null,
        });
        return {
            triggered: false,
            status: 'skipped',
            reason: 'tracking_only_or_missing_choice',
        };
    }

    const sanitizedCustomMenu = sanitizeCustomNutritionMenu(currentProfile?.custom_nutrition_menu);
    const existingMenuCount = await NutritionMenu.countDocuments({
        user: user._id,
        archived: { $ne: true },
    });

    try {
        if (nutritionPlanChoice === 'existing') {
            if (sanitizedCustomMenu.length > 0) {
                const now = new Date();
                await NutritionMenu.insertMany(sanitizedCustomMenu.map((entry) => ({
                    user: user._id,
                    date: now,
                    meal_period: entry.meal_period,
                    meal_name: entry.meal_name,
                    source: 'existing',
                    total_calories: entry.total_calories,
                    total_protein: entry.total_protein,
                    total_carbs: entry.total_carbs,
                    total_fat: entry.total_fat,
                    note: entry.note,
                    foods: entry.foods,
                })));
                user.profile = {
                    ...(user.profile || {}),
                    meal_frequency: countDistinctMealPeriods(sanitizedCustomMenu) || user.profile?.meal_frequency,
                    nutrition_plan_status: 'ready',
                    nutrition_plan_error: undefined,
                    nutrition_plan_source: 'manual',
                    nutrition_plan_generated_at: new Date(),
                };
            } else {
                user.profile = {
                    ...(user.profile || {}),
                    nutrition_plan_status: existingMenuCount > 0 ? 'ready' : 'skipped',
                    nutrition_plan_error: undefined,
                    nutrition_plan_source: 'manual',
                };
            }
            await user.save();
            console.info('onboarding.nutrition.ready', {
                requestId,
                userId: String(user._id),
                trigger,
                choice: 'existing',
                insertedCount: sanitizedCustomMenu.length,
                existingMenuCountBefore: existingMenuCount,
                status: user.profile.nutrition_plan_status,
            });
            return {
                triggered: true,
                status: user.profile.nutrition_plan_status,
                reason: sanitizedCustomMenu.length > 0 ? 'custom_menu_saved' : 'no_custom_menu_provided',
            };
        }

        if (nutritionPlanChoice === 'ai') {
            const existingMenuEntries = await NutritionMenu.find({
                user: user._id,
                archived: { $ne: true },
            })
                .select('source note foods')
                .lean();

            const visibleMenuEntries = existingMenuEntries.filter((entry) => !isLegacyAutogeneratedNutritionMenuEntry(entry));
            const hasVisibleAiMenus = visibleMenuEntries.some((entry) => String(entry?.source || '').trim().toLowerCase() === 'ai');

            if (visibleMenuEntries.length === 0) {
                const generatedAt = new Date();
                const { menuEntries: generatedMenuEntries, reasoning, provider, model } = await onboardingNutritionMenuBuilder.buildOnboardingAiNutritionMenu({
                    profile: currentProfile,
                    likedFoods: user.liked_foods || [],
                    dislikedFoods: user.disliked_foods || [],
                    date: generatedAt,
                    userId: user._id,
                });

                await NutritionMenu.insertMany(generatedMenuEntries.map((entry) => ({
                    user: user._id,
                    date: entry.date,
                    meal_period: entry.meal_period,
                    meal_name: entry.meal_name,
                    source: entry.source,
                    total_calories: entry.total_calories,
                    total_protein: entry.total_protein,
                    total_carbs: entry.total_carbs,
                    total_fat: entry.total_fat,
                    note: entry.note,
                    foods: entry.foods,
                })));

                user.profile = {
                    ...(user.profile || {}),
                    meal_frequency: countDistinctMealPeriods(generatedMenuEntries) || user.profile?.meal_frequency,
                    nutrition_plan_status: 'ready',
                    nutrition_plan_error: undefined,
                    nutrition_plan_source: 'agent',
                    nutrition_plan_generated_at: generatedAt,
                };
                await user.save();
                console.info('onboarding.nutrition.ready', {
                    requestId,
                    userId: String(user._id),
                    trigger,
                    choice: 'ai',
                    existingMenuCountBefore: existingMenuCount,
                    insertedCount: generatedMenuEntries.length,
                    status: user.profile.nutrition_plan_status,
                    reason: 'ai_menu_generated',
                    provider,
                    model,
                    reasoning,
                });

                return {
                    triggered: true,
                    status: user.profile.nutrition_plan_status,
                    reason: 'ai_menu_generated',
                    insertedCount: generatedMenuEntries.length,
                };
            }

            user.profile = {
                ...(user.profile || {}),
                nutrition_plan_status: 'ready',
                nutrition_plan_error: undefined,
                nutrition_plan_source: hasVisibleAiMenus ? 'agent' : 'manual',
                nutrition_plan_generated_at: user.profile?.nutrition_plan_generated_at || new Date(),
            };
            await user.save();
            console.info('onboarding.nutrition.ready', {
                requestId,
                userId: String(user._id),
                trigger,
                choice: 'ai',
                existingMenuCountBefore: existingMenuCount,
                visibleMenuCount: visibleMenuEntries.length,
                status: user.profile.nutrition_plan_status,
                reason: 'existing_visible_menu_preserved',
            });

            return {
                triggered: false,
                status: user.profile.nutrition_plan_status,
                reason: 'existing_visible_menu_preserved',
            };
        }

        console.info('onboarding.nutrition.skipped', {
            requestId,
            userId: String(user._id),
            trigger,
            reason: 'unsupported_nutrition_choice',
            nutritionPlanChoice,
        });
        return {
            triggered: false,
            status: 'skipped',
            reason: 'unsupported_nutrition_choice',
        };
    } catch (error) {
        const errorMessage = cleanText(error?.message || 'Nutrition planner failed.', 400);
        user.profile = {
            ...(user.profile || {}),
            nutrition_plan_status: 'failed',
            nutrition_plan_error: errorMessage,
        };
        await user.save();
        console.error('userController.onboardingNutritionPlanner error:', {
            userId,
            requestId,
            trigger,
            message: errorMessage,
        });
        return {
            triggered: true,
            status: 'failed',
            error: errorMessage,
        };
    }
}

function extractIncomingCustomNutritionMenu(sourceProfile) {
    const source = sourceProfile || {};
    const entries = Array.isArray(source.custom_nutrition_menu) ? source.custom_nutrition_menu : [];
    return sanitizeCustomNutritionMenu(entries);
}

function stripTransientProfileFields(profile = {}) {
    const nextProfile = { ...(profile || {}) };
    delete nextProfile.custom_nutrition_menu;
    return nextProfile;
}

function withTransientMenu(profile = {}, menu = []) {
    if (!Array.isArray(menu) || menu.length === 0) return profile;
    return {
        ...(profile || {}),
        custom_nutrition_menu: menu,
    };
}

function shouldTriggerWorkoutPlannerFromProfilePatch(patch = {}) {
    const source = patch || {};
    const triggerKeys = [
        'onboarding_completed',
        'plan_choice',
        'workout_plan_status',
        'has_existing_plan',
        'custom_plan',
    ];
    return triggerKeys.some((key) => Object.hasOwn(source, key));
}

function shouldTriggerNutritionPlannerFromProfilePatch(patch = {}) {
    const source = patch || {};
    const triggerKeys = [
        'onboarding_completed',
        'nutrition_plan_choice',
        'nutrition_plan_status',
        'custom_nutrition_menu',
    ];
    return triggerKeys.some((key) => Object.hasOwn(source, key));
}

// @desc    Register new user
// @route   POST /api/users
// @access  Public
const registerUser = asyncHandler(async (req, res) => {
    const { name, email, password, profile } = req.body;
    const incomingCustomNutritionMenu = extractIncomingCustomNutritionMenu(profile);

    if (!name || !email || !password) {
        res.status(400);
        throw new Error('Please add all fields');
    }

    const userExists = await User.findOne({ email });

    if (userExists) {
        res.status(400);
        throw new Error('User already exists');
    }

    const user = await User.create({
        name,
        email,
        password,
        profile: normalizeIncomingProfile(stripTransientProfileFields(profile)),
    });

    if (user) {
        await runOnboardingPlannerSafely({
            userId: user.id,
            requestId: req.requestId,
            trigger: 'register',
        });
        await runOnboardingNutritionPlannerSafely({
            userId: user.id,
            requestId: req.requestId,
            trigger: 'register',
            profile: withTransientMenu(user.profile, incomingCustomNutritionMenu),
        });

        const latestUser = await User.findById(user.id);
        res.status(201).json({
            _id: user.id,
            name: latestUser?.name || user.name,
            email: latestUser?.email || user.email,
            profile: latestUser?.profile || user.profile,
            token: generateToken(user.id),
        });
    } else {
        res.status(400);
        throw new Error('Invalid user data');
    }
});

// @desc    Authenticate a user
// @route   POST /api/users/login
// @access  Public
const loginUser = asyncHandler(async (req, res) => {
    const { email, password } = req.body;

    const user = await User.findOne({ email });

    if (user && (await user.matchPassword(password))) {
        res.json({
            _id: user.id,
            name: user.name,
            email: user.email,
            profile: user.profile,
            token: generateToken(user.id),
        });
    } else {
        res.status(401);
        throw new Error('Invalid credentials');
    }
});

// @desc    Get user data
// @route   GET /api/users/me
// @access  Private
const getMe = asyncHandler(async (req, res) => {
    const user = await User.findById(req.user.id);

    if (!user) {
        res.status(404);
        throw new Error('User not found in Database');
    }

    res.status(200).json({
        id: user._id,
        name: user.name,
        email: user.email,
        profile: user.profile
    });
});

// @desc    Update user profile
// @route   PUT /api/users/profile
// @access  Private
const updateProfile = asyncHandler(async (req, res) => {
    const user = await User.findById(req.user.id);
    const shouldTriggerWorkoutPlanner = shouldTriggerWorkoutPlannerFromProfilePatch(req.body);
    const shouldTriggerNutritionPlanner = shouldTriggerNutritionPlannerFromProfilePatch(req.body);
    const incomingCustomNutritionMenu = extractIncomingCustomNutritionMenu(req.body);

    if (!user) {
        res.status(401);
        throw new Error('User not found');
    }

    // Update profile fields
    user.profile = normalizeIncomingProfile({
        ...user.profile,
        ...stripTransientProfileFields(req.body),
    });

    await user.save();
    if (shouldTriggerWorkoutPlanner) {
        await runOnboardingPlannerSafely({
            userId: user.id,
            requestId: req.requestId,
            trigger: 'update_profile',
        });
    }
    if (shouldTriggerNutritionPlanner) {
        await runOnboardingNutritionPlannerSafely({
            userId: user.id,
            requestId: req.requestId,
            trigger: 'update_profile',
            profile: withTransientMenu(user.profile, incomingCustomNutritionMenu),
        });
    }

    const updatedUser = await User.findById(user.id);

    res.status(200).json({
        id: updatedUser._id,
        name: updatedUser.name,
        email: updatedUser.email,
        profile: updatedUser.profile
    });
});

// @desc    Add food preference (like or dislike)
// @route   POST /api/users/food-preference
// @access  Private
const addFoodPreference = asyncHandler(async (req, res) => {
    const { food, action } = req.body; // action: 'like' | 'dislike'

    if (!food || !food.name || !action) {
        res.status(400);
        throw new Error('Please provide food object and action (like/dislike)');
    }

    const user = await User.findById(req.user.id);
    if (!user) {
        res.status(404);
        throw new Error('User not found');
    }

    if (action === 'like') {
        // Remove from disliked if present
        user.disliked_foods = user.disliked_foods.filter(f => f.name !== food.name);
        // Add to liked if not already there
        const alreadyLiked = user.liked_foods.some(f => f.name === food.name);
        if (!alreadyLiked) {
            user.liked_foods.push({
                name: food.name,
                image: food.image || '',
                calories: food.calories || 0,
                protein: food.protein || 0,
                carbs: food.carbs || 0,
                fat: food.fat || 0
            });
        }
    } else if (action === 'dislike') {
        // Remove from liked if present
        user.liked_foods = user.liked_foods.filter(f => f.name !== food.name);
        // Add to disliked if not already there
        const alreadyDisliked = user.disliked_foods.some(f => f.name === food.name);
        if (!alreadyDisliked) {
            user.disliked_foods.push({ name: food.name });
        }
    } else {
        res.status(400);
        throw new Error('Action must be "like" or "dislike"');
    }

    await user.save();

    res.status(200).json({
        liked_count: user.liked_foods.length,
        disliked_count: user.disliked_foods.length
    });
});

// @desc    Get food preferences
// @route   GET /api/users/food-preferences
// @access  Private
const getFoodPreferences = asyncHandler(async (req, res) => {
    const user = await User.findById(req.user.id).select('liked_foods disliked_foods');
    if (!user) {
        res.status(404);
        throw new Error('User not found');
    }

    res.status(200).json({
        liked_foods: user.liked_foods || [],
        disliked_foods: user.disliked_foods || []
    });
});

module.exports = {
    registerUser,
    loginUser,
    getMe,
    updateProfile,
    addFoodPreference,
    getFoodPreferences,
    normalizeIncomingProfile,
    runOnboardingNutritionPlannerSafely,
};
