const AUTO_GENERATED_ONBOARDING_MENU_NOTE = 'Auto-generated onboarding menu';

function isLegacyAutogeneratedNutritionMenuEntry(entry = {}) {
    const source = String(entry?.source || '').trim().toLowerCase();
    const note = String(entry?.note || '').trim();
    const foods = Array.isArray(entry?.foods) ? entry.foods : [];

    return source === 'ai'
        && note === AUTO_GENERATED_ONBOARDING_MENU_NOTE
        && foods.length === 0;
}

module.exports = {
    AUTO_GENERATED_ONBOARDING_MENU_NOTE,
    isLegacyAutogeneratedNutritionMenuEntry,
};
