const test = require('node:test');
const assert = require('node:assert/strict');

const User = require('../models/User');
const NutritionMenu = require('../models/NutritionMenu');
const OnboardingNutritionMenuService = require('../services/onboardingNutritionMenuService');
const {
    AUTO_GENERATED_ONBOARDING_MENU_NOTE,
    isLegacyAutogeneratedNutritionMenuEntry,
} = require('../utils/nutritionMenuUtils');

test('isLegacyAutogeneratedNutritionMenuEntry matches old onboarding placeholder menus', () => {
    assert.equal(isLegacyAutogeneratedNutritionMenuEntry({
        source: 'ai',
        note: AUTO_GENERATED_ONBOARDING_MENU_NOTE,
        foods: [],
    }), true);

    assert.equal(isLegacyAutogeneratedNutritionMenuEntry({
        source: 'ai',
        note: AUTO_GENERATED_ONBOARDING_MENU_NOTE,
        foods: [{ name: 'Chicken Breast' }],
    }), false);
});

test('OnboardingNutritionMenuService creates a real AI menu when only legacy placeholders exist', async () => {
    const originalFindById = User.findById;
    const originalCountDocuments = NutritionMenu.countDocuments;
    const originalFind = NutritionMenu.find;

    try {
        let saveCalls = 0;
        let findCallIndex = 0;
        const fakeUser = {
            _id: 'user-1',
            profile: {
                onboarding_completed: true,
                nutrition_plan_choice: 'ai',
                nutrition_plan_status: 'pending',
                nutrition_plan_source: 'none',
                target_calories: 2400,
                protein_goal: 180,
                carbs_goal: 210,
                fat_goal: 70,
                diet_type: 'everything',
            },
            liked_foods: [],
            disliked_foods: [],
            async save() {
                saveCalls += 1;
            },
        };

        const mockMenuRequest = {
            execute: async () => ({
                createdCount: 4,
                provider: 'test',
                model: 'test-model',
                toolTrace: [],
                response: 'Created 4 menu entries.',
            }),
        };

        User.findById = async () => fakeUser;
        NutritionMenu.countDocuments = async () => 2;

        // First find: initial existingMenuEntries check → all legacy placeholders
        // Second find: savedEntries after generation → 4 real entries
        NutritionMenu.find = () => {
            const callIndex = findCallIndex++;
            return {
                select() { return this; },
                lean: async () => {
                    if (callIndex === 0) {
                        return [
                            { source: 'ai', note: AUTO_GENERATED_ONBOARDING_MENU_NOTE, foods: [] },
                            { source: 'ai', note: AUTO_GENERATED_ONBOARDING_MENU_NOTE, foods: [] },
                        ];
                    }
                    return [
                        { meal_period: 'Breakfast' },
                        { meal_period: 'Lunch' },
                        { meal_period: 'Pre-Workout Snack' },
                        { meal_period: 'Dinner' },
                    ];
                },
            };
        };

        const service = new OnboardingNutritionMenuService({
            menuRequest: mockMenuRequest,
            userModel: User,
            nutritionMenuModel: NutritionMenu,
        });

        const outcome = await service.ensureMenuForUser({
            userId: 'user-1',
            requestId: 'req-1',
            trigger: 'test',
            profile: fakeUser.profile,
        });

        assert.equal(outcome.triggered, true);
        assert.equal(outcome.status, 'ready');
        assert.equal(outcome.reason, 'ai_menu_generated');
        assert.equal(outcome.createdCount, 4);
        assert.equal(fakeUser.profile.nutrition_plan_status, 'ready');
        assert.equal(fakeUser.profile.nutrition_plan_source, 'agent');
        assert.ok(fakeUser.profile.nutrition_plan_generated_at instanceof Date);
        assert.equal(fakeUser.profile.meal_frequency, 4);
        assert.equal(saveCalls, 2); // once for 'generating', once for 'ready'
    } finally {
        User.findById = originalFindById;
        NutritionMenu.countDocuments = originalCountDocuments;
        NutritionMenu.find = originalFind;
    }
});

test('OnboardingNutritionMenuService preserves existing visible AI menus', async () => {
    const originalFindById = User.findById;
    const originalCountDocuments = NutritionMenu.countDocuments;
    const originalFind = NutritionMenu.find;

    try {
        let saveCalls = 0;
        const mockExecute = async () => { throw new Error('execute should not be called'); };
        const fakeUser = {
            _id: 'user-2',
            profile: {
                onboarding_completed: true,
                nutrition_plan_choice: 'ai',
                nutrition_plan_status: 'pending',
                nutrition_plan_source: 'none',
            },
            async save() {
                saveCalls += 1;
            },
        };

        User.findById = async () => fakeUser;
        NutritionMenu.countDocuments = async () => 1;
        NutritionMenu.find = () => ({
            select() { return this; },
            lean: async () => ([
                {
                    source: 'ai',
                    note: 'AI onboarding menu for 2400 kcal/day',
                    foods: [{ name: 'Chicken Breast' }],
                },
            ]),
        });

        const service = new OnboardingNutritionMenuService({
            menuRequest: { execute: mockExecute },
            userModel: User,
            nutritionMenuModel: NutritionMenu,
        });

        const outcome = await service.ensureMenuForUser({
            userId: 'user-2',
            requestId: 'req-2',
            trigger: 'test',
            profile: fakeUser.profile,
        });

        assert.equal(outcome.triggered, false);
        assert.equal(outcome.status, 'ready');
        assert.equal(outcome.reason, 'existing_visible_menu_preserved');
        assert.equal(fakeUser.profile.nutrition_plan_status, 'ready');
        assert.equal(fakeUser.profile.nutrition_plan_source, 'agent');
        assert.equal(saveCalls, 1);
    } finally {
        User.findById = originalFindById;
        NutritionMenu.countDocuments = originalCountDocuments;
        NutritionMenu.find = originalFind;
    }
});

test('OnboardingNutritionMenuService normalizes imported menu periods and avoids duplicate inserts', async () => {
    const originalFindById = User.findById;
    const originalCountDocuments = NutritionMenu.countDocuments;
    const originalFind = NutritionMenu.find;
    const originalInsertMany = NutritionMenu.insertMany;
    const originalUpdateMany = NutritionMenu.updateMany;

    try {
        let saveCalls = 0;
        let insertedDocs = [];
        const fakeUser = {
            _id: 'user-3',
            profile: {
                onboarding_completed: true,
                nutrition_plan_choice: 'existing',
                nutrition_plan_status: 'pending',
                nutrition_plan_source: 'manual',
            },
            async save() {
                saveCalls += 1;
            },
        };

        User.findById = async () => fakeUser;
        NutritionMenu.countDocuments = async () => insertedDocs.filter((doc) => !doc.archived).length;
        NutritionMenu.find = (query = {}) => ({
            select() { return this; },
            lean: async () => {
                if (query.import_origin === 'onboarding_custom_menu') {
                    return insertedDocs
                        .filter((doc) => !doc.archived && doc.import_origin === 'onboarding_custom_menu')
                        .map((doc) => ({ import_signature: doc.import_signature }));
                }
                return [];
            },
        });
        NutritionMenu.insertMany = async (docs) => {
            insertedDocs.push(...docs.map((doc) => ({ ...doc, archived: false })));
            return docs;
        };
        NutritionMenu.updateMany = async () => {
            insertedDocs = insertedDocs.map((doc) => ({ ...doc, archived: true }));
            return { acknowledged: true, modifiedCount: insertedDocs.length };
        };

        const inputProfile = {
            ...fakeUser.profile,
            custom_nutrition_menu: [
                { meal_period: 'Breakfast', meal_name: 'Egg Bowl', total_calories: 420 },
                { meal_period: 'Lunch', meal_name: 'Chicken Rice', total_calories: 610 },
                { meal_period: 'Snack', meal_name: 'Protein Bar', total_calories: 240 },
                { meal_period: 'Dinner', meal_name: 'Steak Plate', total_calories: 680 },
            ],
        };

        const service = new OnboardingNutritionMenuService({
            menuRequest: { execute: async () => { throw new Error('should not call execute for existing path'); } },
            userModel: User,
            nutritionMenuModel: NutritionMenu,
        });

        const firstOutcome = await service.ensureMenuForUser({
            userId: 'user-3',
            requestId: 'req-3a',
            trigger: 'test',
            profile: inputProfile,
        });

        const secondOutcome = await service.ensureMenuForUser({
            userId: 'user-3',
            requestId: 'req-3b',
            trigger: 'test',
            profile: inputProfile,
        });

        assert.equal(firstOutcome.triggered, true);
        assert.equal(firstOutcome.reason, 'custom_menu_saved');
        assert.equal(secondOutcome.triggered, false);
        assert.equal(secondOutcome.reason, 'custom_menu_already_saved');
        assert.equal(insertedDocs.length, 4);
        assert.equal(insertedDocs.some((doc) => doc.meal_period === 'Pre-Workout Snack'), true);
        assert.equal(fakeUser.profile.nutrition_plan_status, 'ready');
        assert.equal(fakeUser.profile.meal_frequency, 4);
        assert.equal(saveCalls, 2);
    } finally {
        User.findById = originalFindById;
        NutritionMenu.countDocuments = originalCountDocuments;
        NutritionMenu.find = originalFind;
        NutritionMenu.insertMany = originalInsertMany;
        NutritionMenu.updateMany = originalUpdateMany;
    }
});
